### ISSUE TITLE
3가지 색상의 보물상자와 문

### ISSUE THREAD

**Issue by simeddk** [simeddk/Tore04_BasicSyntaxCPP#7]
# 열쇠를 획득하고 문을 여는 Doom Style Card Key 구현하기
- 개요 : 3개의 열쇠 상자와 3개의 문
- 내가 원하는 결과(영상) : https://www.youtube.com/watch?v=u_BEuKJeyUo
- 보물상자와 문에 대한 메쉬 에셋, 머티리얼은 수업 시간 중 같이 작업하겠음
- 소스코드 받는 곳 : 없음. 각자 개인 리포지토리를 사용할 것. 가능하면 신규 Branch를 따는걸 추천함
  -> Branch 생성 방법 : https://staticclass.tistory.com/130
  -> github의 기능이 잘 이해가 안 될 때는 반드시 연습용 리포지토리를 만들어놓고 테스트하길 권장함
  -> 연습할 때에는 꼭 언리얼 C++ 프로젝트일 필요는 없고, 간단한 메모장이나 일반 프로젝트로 하면 됨
  -> 위 링크에는 Merge 기능까지 설명되어 있는데, 필요 없고 생성한 Branch에서 마무리 하면 되겠음

- 상세 요구조건
### 1. 보물상자 클래스(C++)
-> 월드 인스턴스의 디테일 패널을 통해 테두리 부분의 색상을 변경할 수 있어야 함
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/6920e171-42b0-4fe9-8b5c-574ea4ef6584)
-> 이런 식으로 빨강, 파랑, 초록색 보물상자를 배치한다

### 2. 보물상자 상호작용
-> `F`키에 대한 액션 이벤트를 정의한다
-> 보물 상자 근처에서 `F`키를 눌렀을 때 보물 상자가 열려야 한다.
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/8ccae5f0-2a5c-4a63-b6a6-11ed9b49fb5d)
-> 이왕이면 보물 상자를 열기 위해 `F`키를 누르라고 안내 문구를 띄워주면 더 좋을 것이다.
-> 타임라인을 C++에서 다루는 방법은 아직 안 배웠기 때문에 뚜껑이 한방에 뙇 하고 열려도 상관 없음

### 3. 키의 획득
-> 빨간 보물상자를 열었다면 빨간 열쇠를 얻을 것. 즉, 각자 보물상자에 상응하는 색상의 열쇠를 획득한다.
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/197c194b-faa5-4311-8e24-6d74d803074c)
-> 열쇠의 획득 상황을 상시 육안으로 확인할 수 있도록 수단과 방법을 가리지 않고 화면에 표시한다.
     (Log, Print, UMG, DrawDebug... 뭐가 되었던)

### 4. 문 클래스(C++)
-> 보물상자와 동일하게 색상 변경 기능을 준다.
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/e2b573fc-5364-4785-ab65-8654aa38c535)

### 5. 문 열리기 작용
-> 같은 색상의 열쇠로만 문을 열 수 있어야 한다.
-> 문을 열 때  `F`키 이벤트를 사용하겠다면 말리지 않겠지만, 열쇠만 있으면 근처에 갔을 때 자동으로 열리게 할 것
-> 해당 열쇠가 없으면 안내 문구를 띄워서 왜 문이 안 열리는지 알려줘야 한다.
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/a54eb972-2a12-4d38-8121-1ea025167563)

### Bonus
-> 위 영상을 보면, 타임라인 없이도 문을 열 때 보간으로 열린다. 선형 뭐시기를 쓰면 할 수 있지 않을까?
-> `F`키 상호 작용 이벤트로 상자 뚜껑을 열고, 열쇠 획득까지는 C++로 하였다.
     그런데 상자 뚜껑이 열릴 때 어떤 추가 이벤트를 블루프린트로 만들 수 있게 해주면 더 좋지 않을까?
     예를 들어 상자를 열 때 추가로 사운드가 재생되거나 파티클이 나오는 꾸미기 이벤트는 굳이 C++로 만드는 것 보다
     블프 사용자가 추가해 주는게 더 유연성이 있을 것 같다. 예를 들어 이런식으로.
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/5514bf14-842a-4afd-94bb-cd37733547de)
어떤 이벤트가 발생할 때 C++에 있는 이벤트와 블루프린트의 이벤트를 다 같이 실행되도록 만들 수는 없을까?

### 6. 제출 방법
기한은 관대하게 1주일(6월 17일까지 완료 바람)
제출은 2가지를 해야 합니다.  
1) 본인의 작업 리포지토리 링크 (당연히 public 이어야 함)
2) 플레이 영상 링크 (유튜브 추천하나 정 뭐하면 카페에 업로드 해도 됨)

### 7. 그 외
-> commit과 push는 몇 번을 하든 상관 없음. 이 기회에 github를 맘껏 사용해보시길
-> 다른 사람과 같이 협업해도 되나요? 가능. 단 이 경우 추가로 pull request, merge 같은 기능을 학습할 필요 있음

**Comment by ehddnjs1200** [comment]
정동원
영상 링크 : https://youtu.be/5nJ8IyO3f18
리포지토리 링크 : https://github.com/ehddnjs1200/UE04_BasicSynatax.git

**Comment by hiki25** [comment]
정의철
영상 : https://youtu.be/7QIylMNYX9s
리포지토리 : https://github.com/hiki25/U04_BasicSyntaxCPP/tree/assingment

**Comment by jslee629** [comment]
이진성
영상: https://youtu.be/m4vVp1WfIF8
리포지토리 링크: https://github.com/jslee629/U04_BasicSyntaxCPP.git

**Comment by Ren-ame** [comment]
김기범
영상 - https://cafe.naver.com/sgagamedev/36522
리포지토리 - https://github.com/Ren-ame/U04_BasicSyntaxCPP/tree/Assignment

**Comment by hyeseo-dev** [comment]
남궁혜서

⚙ GitHub : https://github.com/hyeseo-dev/U04_BasicSyntaxCPP/tree/AM-2
🎞 YouTube : https://youtu.be/j-n1hS5I0f8

**Comment by HyeonLang** [comment]
김재우
영상-https://www.youtube.com/watch?v=PsFXi_6fCiQ

**Comment by yongstar98** [comment]
김용호
영상 : https://cafe.naver.com/sgagamedev/36523?boardType=L
git : https://github.com/yongstar98/U04_BasicSymtaxCPP/tree/Assignment

**Comment by simeddk** [comment]
> 정동원 영상 링크 : https://youtu.be/5nJ8IyO3f18 리포지토리 링크 : https://github.com/ehddnjs1200/UE04_BasicSynatax.git

비트연산자 처리가 특이하군요
