### ISSUE TITLE
재장전 시스템 구현하기

### ISSUE THREAD

**Issue by simeddk** [simeddk/Tore04_BasicSyntaxCPP#8]
- 개요 : 총알이 다 떨어지거나 `R`키를 눌렀을 때 새 탄창으로 갈아 끼우기
- 내가 원하는 결과(영상) : https://youtu.be/Y25GbbxAwtQ
- 상세 요구 조건

### 1. 총알의 소진
-> 총알의 최대 개수는 30개
-> 총을 쏠 때 마다 -1 감소시킬 것
-> 총알이 소진되면 발사 금지시킬 것

### 2. 총알 현황 위젯 표시
-> 위젯을 통해 "잔여 탄수/최대 탄수"를 표시할 것
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/5ab09ceb-20dc-4e96-86fe-d27792de502a)

### 3. 재장전 구현하기
-> 잔여탄수가 0이거나 `R`키를 누르면 재장전 몽타쥬를 재생할 것
-> USkeletalMeshComponent::UnHideBoneByName 함수를 통해 총의 탄창은 숨길 것
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/62e9fd4c-ce49-4ae6-a88c-ed010022a4e7)
-> 새로운 탄창 메쉬를 손에 스폰 시킬 것
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/c985dfa6-6e53-44f1-a24b-dcf01e442a5d)
-> 재장전 완료 후 숨겼던 탄창을 표시하고, 손에 붙었던 탄창을 없앨 것
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/07c82b0f-27ee-4cf8-bd61-ac31b52f8ea6)
-> 소지 탄수가 다시 최대 탄수로 채워질 것
![image](https://github.com/simeddk/Tore04_BasicSyntaxCPP/assets/65766852/15db2c4f-bc5f-4637-b3c7-f7f6ebf8c751)

### 4. 주의 사항
-> 재장전 모션 중에는 Firing, Aim, Equip, Unequip, Reload 안되어야 함

### 5. 제출 방법
-> 브랜치 딸 필요 없음(어차피 Tore04 프로젝트가 완전히 끝났으므로)
-> 마찬가지로 리포지토리(public 주의), 영상 2가지로 올려주세요.

### 6. 참고 소스코드
-> https://github.com/simeddk/Unreal_RifleSystem
-> 언리얼 엔진 4.26으로 작성됨
-> 구식 수업 자료라 소스코드 더러움 주의

**Comment by hyeseo-dev** [comment]
남궁혜서

⚙ GitHub : https://github.com/hyeseo-dev/U04_BasicSyntaxCPP.git
🎞 YouTube : https://youtu.be/7vRMFm1JbL0

**Comment by hiki25** [comment]
⚙ GitHub : https://github.com/hiki25/U04_BasicSyntaxCPP/tree/assingment
🎞 유튜브 : https://youtu.be/Wcke8pRfMFM

**Comment by jslee629** [comment]
이진성
⚙ GitHub : https://github.com/jslee629/U04_BasicSyntaxCPP.git
🎞 Youtube : https://youtu.be/NfB6HfkPAHA

**Comment by Ren-ame** [comment]
김기범
깃허브 : https://github.com/Ren-ame/U04_BasicSyntaxCPP.git
동영상 : https://cafe.naver.com/sgagamedev/36528

**Comment by HyeonLang** [comment]
김재우
영상 : https://youtu.be/wVvAfRhMhUs
깃허브 :

**Comment by yongstar98** [comment]
김용호
깃허브 : https://github.com/yongstar98/U04Assingment-2

문제발생 : 위젯에 현재총알개수가 처음에 총총알개수랑 같은대 0으로 표기되는 문제가 있음
그러면서 에디터가 총알을 발사하는 순간 터지는대 Weapon.cpp ACWeapon::Begin_Reload() 220번줄에 문제가 발생했다는대 해결할려고 시도해봤지만 여전히 원인이 무엇인지 모르겠음

**Comment by simeddk** [comment]
> 김용호 깃허브 : https://github.com/yongstar98/U04Assingment-2
> 
> 문제발생 : 위젯에 현재총알개수가 처음에 총총알개수랑 같은대 0으로 표기되는 문제가 있음 그러면서 에디터가 총알을 발사하는 순간 터지는대 Weapon.cpp ACWeapon::Begin_Reload() 220번줄에 문제가 발생했다는대 해결할려고 시도해봤지만 여전히 원인이 무엇인지 모르겠음

생성자에서는 딜리게이트의 Execute를 할 수가 없습니다.
그리고 해당 OnBulletsCount 라는 딜리게이트에 바인딩 된 함수가 없는것 같은뎁쇼..

**Comment by ehddnjs1200** [comment]
정동원
영상 : https://youtu.be/1g1d_HWj62w
깃허브 : https://github.com/ehddnjs1200/UE04_BasicSynatax.git
